config/routes.rb
Tjh100::Application.routes.draw do



  resources :parties do
    resources :guests, only: [:index, :create, :destroy]
    resources :users, only: :index
  end


  resources :tweets

  devise_for :users

  resources :songs do
    resources :selections, :only => :create
    resources :users, :only => :index
  end

  resources :users do
    member { get 'lock' }
    resources :selections, :only => :index
  end

  resources :selections, :only => [:destroy, :update, :index]

  root :to => "songs#index"

end

app/models/party.rb
class Party < ActiveRecord::Base
  attr_accessible :name

  has_many :guests
  has_many :users, through: :guests
end

app/controllers/parties_controller.rb
class PartiesController < ApplicationController
  def index
    @parties = Party.all
  end

  def show
    @party = Party.find(params[:id])
  end

  def new
    @party = Party.new
  end

  def edit
    @party = Party.find(params[:id])
  end

  def create
    @party = Party.new(params[:party])

      if @party.save
        redirect_to @party, notice: 'Party was successfully created.'
      else
        render action: "new"
      end
  end

  def update
    @party = Party.find(params[:id])

      if @party.update_attributes(params[:party])
     redirect_to @party, notice: 'Party was successfully updated.'
      else
         render action: "edit"
      end
  end

  def destroy
    @party = Party.find(params[:id])
    @party.destroy

      redirect_to parties_url
  end
end

app/helpers/parties_helper.rb
module PartiesHelper
end

app/views/parties/_form.html.haml
= form_for @party do |f|
  - if @party.errors.any?
    #error_explanation
      %h2= "#{pluralize(@party.errors.count, "error")} prohibited this party from being saved:"
      %ul
        - @party.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/parties/edit.html.haml
%h1 Editing party

= render 'form'

= link_to 'Show', @party
\|
= link_to 'Back', parties_path

app/views/parties/index.html.haml
%h1 Listing parties

%table
  %tr
    %th Name
    %th
    %th
    %th

  - @parties.each do |party|
    %tr
      %td= party.name
      %td= link_to 'Show', party
      %td= link_to 'Edit', edit_party_path(party)
      %td= link_to 'Destroy', party, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Party', new_party_path

app/views/parties/new.html.haml
%h1 New party

= render 'form'

= link_to 'Back', parties_path

app/views/parties/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @party.name

= link_to 'Guests', party_users_path(@party)

= link_to 'Edit', edit_party_path(@party)
\|
= link_to 'Back', parties_path