config/routes.rb
Tjh100::Application.routes.draw do



  resources :parties do
    resources :guests, only: [:index, :create, :destroy]
    resources :users, only: :index
  end


  resources :tweets

  devise_for :users

  resources :songs do
    resources :selections, :only => :create
    resources :users, :only => :index
  end

  resources :users do
    member { get 'lock' }
    resources :selections, :only => :index
  end

  resources :selections, :only => [:destroy, :update, :index]

  root :to => "songs#index"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me

  validates :name, presence: true

  has_many :selections, dependent: :destroy
  has_many :songs, :through => :selections
  has_many :guests

  def max_selections
    selections.count >= Selection::SELECTION_QTY
  end

  def self.recalculate_scores
    User.all.each do |user|
      user.calculate_score
    end
    if Song.find_by_position(1)
      calculate_number1
    end
  end

  def calculate_score
    total = songs.inject(0) do |score, song|
      score += (101 - song.position) if song.position
      score
    end
    self.update_attribute(:score, total)
  end

  def display_picks
    admin? || locked?
  end

  def ok_to_submit?
    selections.count == Selection::SELECTION_QTY && number1_selected?
  end

  def number1_selected?
    selections.where(:number_one => true).count !=0
  end

  def self.number_submitted
    User.where(locked: true).count
  end

  def display_name_and_submitted
    if locked?
      name + " (submitted)"
    else
      name
    end
  end

  def self.calculate_number1

    top_hit = Selection.joins(:song).where(number_one: true).order(:position).first

    Selection.where(number_one: true, song_id: top_hit.song_id).each do |selection|
      p selection.user
      selection.user.update_attribute(:score, selection.user.score + Selection::NUMBER1_BONUS )
    end




    #for i in 1..100
    #  song = Song.find_by_position(i)
    #  selections = Selection.where(:song_id => song, :number_one => true)
    #  #p song
    #  #p selections
    #  if selections
    #    selections.each do |selection|
    #      #p selection
    #      selection.user.score += Selection::NUMBER1_BONUS
    #    end
    #    break
    #  end
    #end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @song = Song.find_by_id(params[:song_id])
    @party = Party.find_by_id(params[:party_id])
    case

      when @song
        @users = @song.users.order(:name)
      when @party
        @users = @party.users.order(:name)
      else
        @users = User.order(:score).reverse
    end
  end



  def show
    @user = User.find(params[:id])
    @selections = @user.selections
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    @user = User.find(params[:id])

    if params[:user][:password].blank? ? @user.update_without_password(params[:user]) : @user.update_attributes(params[:user])
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to users_url
  end

  def lock
    @user = User.find(params[:id])

    if current_user.admin?
      @user.update_attribute(:locked, true)
      redirect_to user_selections_path(@user)
    else
      if current_user == @user
        @user.update_attribute(:locked, true)
        redirect_to user_selections_path(@user)
      else
        redirect_to new_user_session_path
      end
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
= form_for @user do |f|
  -if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :password
    = f.password_field :password
  .field
    = f.label :password_confirmation
    = f.password_field :password_confirmation
  .actions
    = f.submit 'Save'

app/views/users/_index.html.haml
.container.content
  - if @song
    %h1#song_title Who picked #{link_to @song.name_and_artist, @song}
  - else
    %h1 Player Listing

%table.table.table-striped
  %tr
    %th pos
    %th Name
    %th QTY Picked
    %th # songs
    %th Score
    - if current_user.admin? && !@song
      %th
  - pos = 1
  - @users.each do |user|
    %tr
      %td= pos
      %td= link_to_if current_user.locked?, user.display_name_and_submitted, user_selections_path(user), id: "show_selections"
      %td.right
        - if user.selections.length > 0
          = link_to_if((can? :show, user), pluralize(user.selections.length, 'selection'), user_selections_path(user))
      %td.right= user.songs.where(position: 1..100).length
      %td.right= user.score
      - if current_user.admin? && !@song
        %td.actions
          .actions#remove_user= link_to "Delete", user_path(user), :method => :delete, :class => 'btn btn-mini btn-danger', id: "delete_link"
      - if @guest
        %td.actions
          .actions= link_to "Add", party_guests_path(@party, user_id: user), :method => :post, :class => 'btn btn-mini btn-danger'
      - else
        - if @party
          %td.actions
            .actions= link_to "Delete", party_guest_path(@party, user), :method => :delete, :class => 'btn btn-mini btn-danger'

      - pos += 1
%br
- if can?(:add, User) && @song.nil?
  = link_to 'New User', new_user_path, id: "new_link"


- if @party && !@guest
  = link_to 'Add Guests', party_guests_path(@party)

- if @guest
  = link_to 'Party Guests', party_users_path(@party)

app/views/users/edit.html.haml
.container.content
  %h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
= render 'index'

app/views/users/new.html.haml
.container.content
  %h1 New user

= render 'form'

= link_to 'Back', users_path

app/views/users/show.html.haml
.container.content
  %p#notice= notice

%p
  %b Name:
  = @user.name
%p
  %b email:
  = @user.email

- if can? :show, @user
  = link_to "Selected Songs", user_selections_path(@user)

%p
  - if can? :update, @user
    = link_to 'Edit', edit_user_path(@user), id: "edit_link"