config/routes.rb
Tjh100::Application.routes.draw do



  resources :parties do
    resources :guests, only: [:index, :create, :destroy]
    resources :users, only: :index
  end


  resources :tweets

  devise_for :users

  resources :songs do
    resources :selections, :only => :create
    resources :users, :only => :index
  end

  resources :users do
    member { get 'lock' }
    resources :selections, :only => :index
  end

  resources :selections, :only => [:destroy, :update, :index]

  root :to => "songs#index"

end

app/models/song.rb
require 'csv'

class Song < ActiveRecord::Base
  has_many :selections
  has_many :users, :through => :selections

  validates_presence_of :name
  validates_presence_of :artist

  after_update :recalculate_users

  def recalculate_users
    User.recalculate_scores
  end

  def name_and_artist
    "#{name} - #{artist}"
  end

  def points
    101 - position if position
  end

  # TODO: seank remove the below, now housed in lib/song_scraper.rb
  def self.scrape_songs
    require 'open-uri'
    for i in 0..26
      url = "https://hottest100.triplej.net.au/artist/start/#{i}"
      doc = Nokogiri::HTML(open(url))

      list = doc.at("div .IndexPageContent")
      if list
        list = list.at("p")

        list.css("span .artist").each do |item|
          unless item.next_element.next_element.next_element.attribute('data-hash').value.blank?
            Song.create(name: item.next_element.next_element.text.strip, artist: item.text.strip)
            #p item.next_element.next_element.text.strip
            #p item.text.strip
          end
        end
      end
    end
  end

  #Change with website in 2016 has the punter having to authenticate first
  def self.import_songs
    CSV.foreach("db/tjh100_2018.csv") do |line|
      Song.create(name: line[1].strip, artist: line[0].strip)
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me

  validates :name, presence: true

  has_many :selections, dependent: :destroy
  has_many :songs, :through => :selections
  has_many :guests

  def max_selections
    selections.count >= Selection::SELECTION_QTY
  end

  def self.recalculate_scores
    User.all.each do |user|
      user.calculate_score
    end
    if Song.find_by_position(1)
      calculate_number1
    end
  end

  def calculate_score
    total = songs.inject(0) do |score, song|
      score += (101 - song.position) if song.position
      score
    end
    self.update_attribute(:score, total)
  end

  def display_picks
    admin? || locked?
  end

  def ok_to_submit?
    selections.count == Selection::SELECTION_QTY && number1_selected?
  end

  def number1_selected?
    selections.where(:number_one => true).count !=0
  end

  def self.number_submitted
    User.where(locked: true).count
  end

  def display_name_and_submitted
    if locked?
      name + " (submitted)"
    else
      name
    end
  end

  def self.calculate_number1

    top_hit = Selection.joins(:song).where(number_one: true).order(:position).first

    Selection.where(number_one: true, song_id: top_hit.song_id).each do |selection|
      p selection.user
      selection.user.update_attribute(:score, selection.user.score + Selection::NUMBER1_BONUS )
    end




    #for i in 1..100
    #  song = Song.find_by_position(i)
    #  selections = Selection.where(:song_id => song, :number_one => true)
    #  #p song
    #  #p selections
    #  if selections
    #    selections.each do |selection|
    #      #p selection
    #      selection.user.score += Selection::NUMBER1_BONUS
    #    end
    #    break
    #  end
    #end
  end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource :song

  def index
    @search = Song.search(params[:search])
    @songs = @search.page(params[:page]).per(20).order(:name)
    @song_ids = current_user.selections.map &:song_id
  end

  def show
    @song = Song.find(params[:id])
  end

  def new
    @song = Song.new
  end

  def edit
    @song = Song.find(params[:id])
  end

  def create
    @song = Song.new(params[:song])

    if @song.save
      redirect_to @song, notice: 'Song was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    @song = Song.find(params[:id])

    if @song.update_attributes(params[:song])
      redirect_to @song, notice: 'Song was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @song = Song.find(params[:id])
    @song.destroy

    redirect_to songs_url
  end
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/songs/_form.html.haml
= form_for @song do |f|
  -if @song.errors.any?
    #error_explanation
      %h2= "#{pluralize(@song.errors.count, "error")} prohibited this song from being saved:"
      %ul
        - @song.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :artist
    = f.text_field :artist
  .field
    = f.label :position
    = f.number_field :position
  .actions
    = f.submit 'Save'

app/views/songs/edit.html.haml
.container.content
  %h1 Editing song

= render 'form'

= link_to 'Show', @song
\|
= link_to 'Back', songs_path

app/views/songs/index.html.haml
%h1 Pick your Songs

.navbar
  .navbar-inner
    = form_for @search, :html => { :class => 'navbar-form' } do |f|
      = f.text_field :name_contains, :placeholder => 'Name of song'
      = f.text_field :artist_contains, :placeholder => 'Artist'
      = f.submit "Filter list", :class => 'btn'

%table.table.table-striped
  %tr
    %th= sort_link @search, :name
    %th= sort_link @search, :artist
    - if current_user.locked?
      %th Position
      - if current_user.locked?
        %th#picks_title Picks
    - else
      %td

  - @songs.each do |song|
    %tr
      %td= link_to_if(current_user.admin?, song.name, edit_song_path(song), id: "song_link")
      %td= song.artist
      - if current_user.locked?
        %td.center= song.position
        - if current_user.locked?
          %td.center#picks_data
            - if song.selections.length > 0
              = link_to pluralize(song.selections.length, 'person', 'people'), song_users_path(song)
      - unless current_user.locked?
        - if @song_ids.include? song.id
          %td.actions= link_to 'Unpick', selection_path(song), :method => :delete, :class => 'btn btn-mini btn-danger', id: "change_pick"
        - else
          %td.actions= link_to_unless current_user.max_selections, 'Pick', song_selections_path(song), :method => :post, :class => 'btn btn-mini btn-success', id: "change_pick"

= paginate @songs

app/views/songs/new.html.haml
%h1 New song

= render 'form'

= link_to 'Back', songs_path

app/views/songs/show.html.haml
.container.content
  %p#notice= notice

%p
  %b Name:
  = @song.name
%p
  %b Artist:
  = @song.artist
%p
  %b Position:
  = @song.position

%p
  %b Picked by:
  - if current_user.display_picks
    = link_to "#{@song.selections.length} users", song_users_path(@song)
  - else
    Not Available until you lock your selections

- if can? :update, @song
  = link_to 'Edit', edit_song_path(@song), id: "edit_link"