config/routes.rb
Tjh100::Application.routes.draw do



  resources :parties do
    resources :guests, only: [:index, :create, :destroy]
    resources :users, only: :index
  end


  resources :tweets

  devise_for :users

  resources :songs do
    resources :selections, :only => :create
    resources :users, :only => :index
  end

  resources :users do
    member { get 'lock' }
    resources :selections, :only => :index
  end

  resources :selections, :only => [:destroy, :update, :index]

  root :to => "songs#index"

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title TJH100
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
    
  %body
    - if user_signed_in?
      .navbar.navbar-fixed-top.navbar-inverse
        .navbar-inner
          = link_to 'Triple J Hottest 100', songs_path, :class => 'brand'
          %ul.nav
            %li= link_to "All Songs", songs_path
            - if current_user.locked?
              %li#all_selections_menu= link_to "All Selections", selections_path
            %li= link_to "My Songs", user_selections_path(current_user)
            %li= link_to "Results", tweets_path
            %li= link_to "Players", users_path
            %li= link_to "My Profile", user_path(current_user)
            %li= link_to "Logout (#{current_user.name})", destroy_user_session_path, :method => :delete
            - if current_user.admin?
              %li= link_to "Switch to Game Day", id: "game_day"
      .container.content
        %h3
          Submission of picks stops Sunday 21 Jan 10:00 PM
        Welcome #{current_user.name}, There are #{(Date.new(2018, 1, 27) - Date.today).to_i} days until game day, and there are
        #{User.all.count} registered players with #{User.number_submitted} of these already submitted their picks.
        %p
        You have picked #{current_user.selections.length} of #{Selection::SELECTION_QTY} songs
        - if !current_user.number1_selected?
          and you need to pick a number 1
        - if current_user.locked?
          and you have submitted your songs. There are a total of #{Selection.all.map(&:song_id).uniq.count} different songs selected
        - else
          - if current_user.ok_to_submit?
            = link_to "Submit Your Songs", lock_user_path(current_user), confirm: "Make sure you are happy with your songs as you can't change this later. Are you sure?",
            id: "user_lock", :class => 'btn btn-mini btn-success'

    .container
      - if notice
        .alert.alert-info= notice
      - if alert
        .alert= alert
      = yield